### ISSUE TITLE
Ubuntu 16.04.1 LTS build issue

### ISSUE THREAD

**Issue by orekdm** [hrbrmstr/ipv4-heatmap#1]
Default Makefile produces the following error:
//lib/x86_64-linux-gnu/libm.so.6: error adding symbols: DSO missing from command line

Adding "-lm" to Makefile stanza fixes the problem.
ipv4-heatmap: ${OBJS}
        ${CC} ${LDFLAGS} -o $@ ${OBJS} ${LIBS} -lm

**Comment by hrbrmstr** [comment]
thx. i'll update the build.
