### ISSUE TITLE
The iana-labels.txt is empty.

### ISSUE THREAD

**Issue by blackswanburst** [hrbrmstr/ipv4-heatmap#2]
I love using this tool with labels, and I love the new palette so thanks for the hard work. I used the labels previously, and much prefer to continue to do so. I have a copy from the previous version of the IPv4 Heatmap code, so we can resolve this easily.

Either I can fork and add the file for you to pull it, or you can download the older version here:
http://maps.measurement-factory.com/software/releases/ipv4-heatmap-20110505.tar.gz
And use the filled annotations files from that release in your code here.
I can confirm in advance that is still works with the old annotation file.

Keep on rawking!

**Comment by hrbrmstr** [comment]
oh if you could PR it that'd be +1. I'll get it merged as soon as you do.
